name: Deploy
on:
  push:
    branches:
      - master

env:
  DEP_PATH: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check out master
        uses: actions/checkout@master

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master

      - name: Solve Conflict
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: "comp7940-lab5-21437254"  # Rename this to the app of your Heroku app.
        run: git fetch --unshallow https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

      - name: Deploy
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: "comp7940-lab5-21437254"  # Rename this to the app of your Heroku app.
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master  
